# Generated by Django 2.2.4 on 2019-11-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personId', models.CharField(blank=True, max_length=50)),
                ('header', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('task_date', models.CharField(blank=True, max_length=20)),
                ('task_time', models.CharField(blank=True, max_length=20)),
                ('important', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
