# Generated by Django 2.2.4 on 2019-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='minutes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='one_day',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='one_hour',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='remind_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='remind_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='important',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
