# Generated by Django 2.2.4 on 2019-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20191108_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='pred_del',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
