# Generated by Django 2.2.4 on 2019-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_auto_20191112_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(blank=True, max_length=200)),
                ('mini_mode', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
