# Generated by Django 2.2.4 on 2020-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='token',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend1_img',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend1_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend1_surname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend2_img',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend2_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend2_surname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend3_img',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend3_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend3_surname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend4_img',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend4_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend4_surname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend5_img',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend5_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='friend5_surname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_img',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
